# Generated by Django 4.1.7 on 2023-04-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_remove_menu_kategori_menu_kategoris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='kategoris',
            field=models.ManyToManyField(blank=True, null=True, to='adminpage.kategorimenu'),
        ),
    ]
