# Generated by Django 4.1.7 on 2023-04-02 02:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0005_peminat_alter_menu_kategoris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminat',
            name='no_wa',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
