# Generated by Django 4.1.7 on 2023-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0007_katalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog',
            name='file',
            field=models.FileField(default='a', upload_to='katalog/'),
            preserve_default=False,
        ),
    ]
