# Generated by Django 4.1.7 on 2023-04-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0008_katalog_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='tipe',
            field=models.CharField(choices=[('biasa', 'biasa'), ('khusus', 'khusus')], default='biasa', max_length=255, unique=True),
        ),
    ]
