# Generated by Django 4.1.7 on 2023-04-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0009_alter_katalog_tipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('gambar', models.FileField(upload_to='berita/')),
                ('menuju_ke', models.URLField(blank=True, max_length=255, null=True)),
                ('konten', models.TextField()),
                ('show_header', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='katalog',
            name='tipe',
            field=models.CharField(choices=[('biasa', 'biasa'), ('khusus', 'khusus')], max_length=255, unique=True),
        ),
    ]
