# Generated by Django 4.1.7 on 2023-04-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0010_berita_alter_katalog_tipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
