# Generated by Django 4.1.7 on 2023-04-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0011_alter_berita_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeminatCaraMenemukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='peminat',
            name='alamat',
            field=models.TextField(default='Surakarta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminat',
            name='cara_menemukan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpage.peminatcaramenemukan'),
        ),
    ]
