# Generated by Django 4.1.7 on 2023-04-11 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0012_peminatcaramenemukan_peminat_alamat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminat',
            name='jumlah_kebutuhan',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminat',
            name='waktu_kebutuhan',
            field=models.CharField(choices=[('hari', 'Per Hari'), ('minggu', 'Per Minggu')], default='hari', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminatcaramenemukan',
            name='has_isian',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='IsianPeminatCaraMenemukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isian', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cara_menemukan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpage.peminatcaramenemukan')),
                ('peminat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpage.peminat')),
            ],
        ),
    ]
