# Generated by Django 4.1.7 on 2023-04-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0013_peminat_jumlah_kebutuhan_peminat_waktu_kebutuhan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='range_harga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
