# Generated by Django 4.1.7 on 2023-04-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0014_menu_range_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminat',
            name='id_number',
            field=models.CharField(default='MGB1HQ', max_length=255),
            preserve_default=False,
        ),
    ]
